### ISSUE TITLE
USER STORY Register an Account

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#1]
As a **user**, I can **register an account** so that I can **gain access to the full range of features** of the blog.

**Acceptance Criteria:**
•	1:  User can register a new account
•	2: User can have access to all features of the blog

**Tasks**

- [x] Task 1. Install Allauth 
- [x] Task 2: Update requirements, urls files
- [x] Task 3. Create a Sign-Up section link in Nav Bar
- [x] Task 4. Edit Signup forms using allauth & crispy forms
- [x] Task 5. Use flash alerts to give user feedback.
- [x] Task 6. Create rules so that registered and logged-in users can create, edit, comment, and like posts.
