### ISSUE TITLE
USER STORY Read a blog post

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#10]
As a **user** I can **I can click on a blog post** so that **I can read the full detailed blog post**

**Acceptance Criteria:**
•	1: User can click on the paginated blog post list and read the full detailed blog post

**Tasks**
- [x] Task 1. Create PostList View
- [x] Task 2. Create html page, that will be  paginated
- [x] Task 3. Wire up the urls
