### ISSUE TITLE
USER STORY Comment on posts

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#11]
As a **user** I can **comment on trail posts** so that **I can give my feedback & opinion to other users**

**Acceptance Criteria:**
•	1: User can make a comment on the blog post
•	2: User only can only make a comment if they are a registered user.

**Task**
- [x] Task 1. Add comment function to the post view.
- [x] Task 2. Integrate into Html via crispy forms.
- [x] Task 3. Add authenticated rule so only logged-in users can comment on posts.
- [x] Task 4. Users gets an alert message that a comment has been submitted and is waiting approval
