### ISSUE TITLE
USER STORY View Number of Likes

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#13]
As a **user** I can **view the number of likes on a blog post** so that **I can see which is the most popular hiking trail**

**Acceptance Criteria:**
•	1: user can view the total number of likes given to an individual blog post

**Tasks**
- [x] Task 1. Create view PostLike
- [x] Task 2. Integrate into post detail Html
- [x] Task 3. User has to be authenticated in order to like a post
