### ISSUE TITLE
USER STORY Landing page

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#15]
As a **user** I can **understand the website's purpose quickly** so that **I know if its what I'm looking for**

**Acceptance Criteria:**
•	1: User can quickly understand website's purpose and what to do next from the homepage of the website

**Tasks**

- [x] Task 1. Create Wire frame of landing page.
- [x] Task 2. Create nav bar and footer and basic layout with bootstrap.
- [x] Task 3. Create hero image.
- [x] Task 4. Check responsiveness.
