### ISSUE TITLE
USER STORY Online Shop

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#18]
As a **user** I can **buy hiking equipment from the website** so that ** I can be prepared for my next hike based on user's comments & recommendations**

**Acceptance Criteria:**
•	1: user can buy hiking related equipment and clothing from the website

**Tasks:**

- [ ] Task 1. Create a new app
- [ ] Task 2. Create Models for new shop products
- [ ] Task 3. Create views and wire up urls
