### ISSUE TITLE
USER STORY Login/Logout of the site

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#2]
As a **registered user** I can **easily login and logout of the blog** so that I can **access the content i have created**.

**Acceptance Criteria:**
•	1: User can easily login and logout of the site

**Tasks:**

- [x] Task 1. Create login in the nav bar.
- [x] Task 2. Connect URLs so the user is redirected to the home page after logging in.
- [x] Task 3. Welcome name of the user on the home page when redirected and the user name is also displayed in nav bar.
- [x] Task 4. Edit allauth login in form
