### ISSUE TITLE
USER STORY Admin CRUD

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#3]
As an **Admin** I can **view, create, edit, update and delete all blog posts ** so that the Admin can **easily moderate and control the website's content.**

**Acceptance Criteria:**
•	1: Admin can delete posts
•	2: Admin can edit posts
•	3: Admin can filter posts 
•	4: Admin can search posts

**Tasks**

- [x] Task 1. Create an admin superuser.
- [x] Task 2.  Set up post and user views on the admin page
- [x] Task 3. Set up filtering & Searching of posts and comments on the admin page
- [x] Task 4 Integrate Summernote into the admin page
- [x] Task 5 admin can manage, create, update, read & delete posts & approve comments of users
