### ISSUE TITLE
USER STORY View list of Blog Posts

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#5]
As a **user** I can view a **list of trails blog posts** so that I can see **easily move through the list of trails and pick one I want to read**

**Acceptance Criteria**:
•	1: Trails appear in the paginated list 

**Tasks**

- [x] Task 1. Create PostList view
- [x] Task 2. Create html page and layout
- [x] Task 3. Wire up urls
