### ISSUE TITLE
USER STORY Delete blog post

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#8]
As a **user** I can **delete blog posts i have created** so that **I can remove any unwanted trail posts I have made**

**Acceptance Criteria:**
•	1: User can delete blog posts they have created from the website.
•	2: User can only delete their own content linked to their registered account.

**Tasks**
- [x] Task 1. Create a Delete view,delete Html and wire up URLs
- [x] Task 2. Create a rule so that the logged-in user must be the same as the author if they want to delete a post.
- [x] Task 3. Add buttons to post list and post detail pages, which will only be visible if the logged-in user created the post.
- [x] Task 4. Once post is deleted the user will be returned to the home page
