### ISSUE TITLE
USER STORY Edit blog post

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/hiking-hub#9]
As a **user** I can **edit my trail blog post** so that **I can update or make changes to my post**

**Acceptance Criteria:**
•	1: User can make edits and updates to a previously published blog post
•	2: User can only their own content

**Tasks**
- [x] Task 1. Create a Update view,Update Html and wire up URLs
- [x] Task 2. Create a rule so that the logged-in user must be the same as the author if they want to update a post.
- [x] Task 3. Add update buttons to post list and post detail pages, which will only be visible if the logged-in user created the post.
- [x] Task 4. An alert message pops on the screen saying post has been updated
- [x] Task 5. Once the post is updated the user will be returned to the post list page
